# Generated by Django 4.2.1 on 2023-06-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_num', models.CharField(max_length=10)),
                ('curr_color', models.CharField(max_length=10)),
                ('target_color', models.CharField(max_length=10)),
            ],
        ),
    ]
